### ISSUE TITLE
Move Action Behaving Inconsistently

### ISSUE THREAD

**Issue by jjentges** [blue-prism/ms-outlook-utility#3]
When I use the Move Email to Inbox Sub Folder action, emails do not always move as intended. Sometimes emails are duplicated, sometimes emails disappear, sometimes emails don't move at all (and the VBO doesn't throw an error), and sometimes emails move to the correct location. For disappearing emails, if I go to the Deleted Items folder and recover items recently removed from that folder, I can find the email that disappeared in that view; the time stamp of deletion coincides with when the Move action ran with the VBO.

**Comment by EricWilson-BluePrism** [comment]
Hi @jjentges. Thanks for reaching out. We're looking into it.

**Comment by EricWilson-BluePrism** [comment]
@jjentges,

Can you provide some more details about your environment? What versions of Outlook and Exchange are being used? Are the folders you're trying to move messages to Shared folder? Is Cached Mode enabled on your system?

Cheers,
Eric

**Comment by EricWilson-BluePrism** [comment]
Closing this issue as there's been no response from the author.
